<?php

namespace Container7cTHx5v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MeSNjDkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MeSNjDk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MeSNjDk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ApiStatusController::index' => ['privates', '.service_locator.rh_HRCQ.App\\Controller\\ApiStatusController::index()', 'getApiStatusControllerindexService', true],
            'App\\Controller\\CoursController::index' => ['privates', '.service_locator.43tWQYB.App\\Controller\\CoursController::index()', 'getCoursControllerindexService', true],
            'App\\Controller\\StatusController::index' => ['privates', '.service_locator.C_gVBbj.App\\Controller\\StatusController::index()', 'getStatusControllerindexService', true],
            'App\\Controller\\StatusController::creerStatus' => ['privates', '.service_locator.43tWQYB.App\\Controller\\StatusController::creerStatus()', 'getStatusControllercreerStatusService', true],
            'App\\Controller\\StatusController::supprimerStatus' => ['privates', '.service_locator.0bG7vKf.App\\Controller\\StatusController::supprimerStatus()', 'getStatusControllersupprimerStatusService', true],
            'App\\Controller\\StatusController::modifierStatus' => ['privates', '.service_locator.0bG7vKf.App\\Controller\\StatusController::modifierStatus()', 'getStatusControllermodifierStatusService', true],
            'App\\Controller\\TypeAbonnementController::index' => ['privates', '.service_locator.43tWQYB.App\\Controller\\TypeAbonnementController::index()', 'getTypeAbonnementControllerindexService', true],
            'App\\Controller\\UserApiController::createUser' => ['privates', '.service_locator.43tWQYB.App\\Controller\\UserApiController::createUser()', 'getUserApiControllercreateUserService', true],
            'App\\Controller\\UserController::createUser' => ['privates', '.service_locator.43tWQYB.App\\Controller\\UserController::createUser()', 'getUserControllercreateUserService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ApiStatusController:index' => ['privates', '.service_locator.rh_HRCQ.App\\Controller\\ApiStatusController::index()', 'getApiStatusControllerindexService', true],
            'App\\Controller\\CoursController:index' => ['privates', '.service_locator.43tWQYB.App\\Controller\\CoursController::index()', 'getCoursControllerindexService', true],
            'App\\Controller\\StatusController:index' => ['privates', '.service_locator.C_gVBbj.App\\Controller\\StatusController::index()', 'getStatusControllerindexService', true],
            'App\\Controller\\StatusController:creerStatus' => ['privates', '.service_locator.43tWQYB.App\\Controller\\StatusController::creerStatus()', 'getStatusControllercreerStatusService', true],
            'App\\Controller\\StatusController:supprimerStatus' => ['privates', '.service_locator.0bG7vKf.App\\Controller\\StatusController::supprimerStatus()', 'getStatusControllersupprimerStatusService', true],
            'App\\Controller\\StatusController:modifierStatus' => ['privates', '.service_locator.0bG7vKf.App\\Controller\\StatusController::modifierStatus()', 'getStatusControllermodifierStatusService', true],
            'App\\Controller\\TypeAbonnementController:index' => ['privates', '.service_locator.43tWQYB.App\\Controller\\TypeAbonnementController::index()', 'getTypeAbonnementControllerindexService', true],
            'App\\Controller\\UserApiController:createUser' => ['privates', '.service_locator.43tWQYB.App\\Controller\\UserApiController::createUser()', 'getUserApiControllercreateUserService', true],
            'App\\Controller\\UserController:createUser' => ['privates', '.service_locator.43tWQYB.App\\Controller\\UserController::createUser()', 'getUserControllercreateUserService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ApiStatusController::index' => '?',
            'App\\Controller\\CoursController::index' => '?',
            'App\\Controller\\StatusController::index' => '?',
            'App\\Controller\\StatusController::creerStatus' => '?',
            'App\\Controller\\StatusController::supprimerStatus' => '?',
            'App\\Controller\\StatusController::modifierStatus' => '?',
            'App\\Controller\\TypeAbonnementController::index' => '?',
            'App\\Controller\\UserApiController::createUser' => '?',
            'App\\Controller\\UserController::createUser' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ApiStatusController:index' => '?',
            'App\\Controller\\CoursController:index' => '?',
            'App\\Controller\\StatusController:index' => '?',
            'App\\Controller\\StatusController:creerStatus' => '?',
            'App\\Controller\\StatusController:supprimerStatus' => '?',
            'App\\Controller\\StatusController:modifierStatus' => '?',
            'App\\Controller\\TypeAbonnementController:index' => '?',
            'App\\Controller\\UserApiController:createUser' => '?',
            'App\\Controller\\UserController:createUser' => '?',
        ]);
    }
}
