<?php

namespace Container7cTHx5v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.43tWQYB.App\Controller\CoursController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.43tWQYB'] ?? $container->load('get_ServiceLocator_43tWQYBService'));

        if (isset($container->privates['.service_locator.43tWQYB.App\\Controller\\CoursController::index()'])) {
            return $container->privates['.service_locator.43tWQYB.App\\Controller\\CoursController::index()'];
        }

        return $container->privates['.service_locator.43tWQYB.App\\Controller\\CoursController::index()'] = $a->withContext('App\\Controller\\CoursController::index()', $container);
    }
}
