<?php

namespace Container7cTHx5v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatusControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C_gVBbj.App\Controller\StatusController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C_gVBbj.App\\Controller\\StatusController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repoStatus' => ['privates', 'App\\Repository\\StatusRepository', 'getStatusRepositoryService', true],
        ], [
            'repoStatus' => 'App\\Repository\\StatusRepository',
        ]))->withContext('App\\Controller\\StatusController::index()', $container);
    }
}
