<?php

namespace Container7cTHx5v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatusControllermodifierStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0bG7vKf.App\Controller\StatusController::modifierStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0bG7vKf.App\\Controller\\StatusController::modifierStatus()'] = ($container->privates['.service_locator.0bG7vKf'] ?? $container->load('get_ServiceLocator_0bG7vKfService'))->withContext('App\\Controller\\StatusController::modifierStatus()', $container);
    }
}
