<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3t3MEIP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3t3MEIP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3t3MEIP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3t3MEIP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3t3MEIP\App_KernelDevDebugContainer([
    'container.build_hash' => '3t3MEIP',
    'container.build_id' => 'e1b7ca17',
    'container.build_time' => 1732703252,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3t3MEIP');
