<?php

namespace Container3t3MEIP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiStatusControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rh_HRCQ.App\Controller\ApiStatusController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rh_HRCQ.App\\Controller\\ApiStatusController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repoStatus' => ['privates', 'App\\Repository\\StatusRepository', 'getStatusRepositoryService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
        ], [
            'repoStatus' => 'App\\Repository\\StatusRepository',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\ApiStatusController::index()', $container);
    }
}
